version: 1
disable_existing_loggers: True

formatters:
  simple:
    format: '[%(levelname)s] %(asctime)s, %(name)s : %(message)s'
    datefmt: '%j %H:%M:%S'  # Julian day, 24-hour clock
    
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: '/Users/Shared/SharedProjects/Projects/LastRecentlyUsedDataBase/LRUdb/logs/lru_database.log' # Specify the log file name here
    mode: 'w' # 'a' for append, 'w' for overwrite

loggers:
  App:
    level: DEBUG
    handlers: [file]
    propagate: no

  LRU_db:
    level: DEBUG
    handlers: [file]
    propagate: no

  LRU:
    level: DEBUG
    handlers: [file]
    propagate: no

  DataBase:
    level: DEBUG
    handlers: [file]
    propagate: no

root:
  level: DEBUG
  handlers: [file]
